version: '3.4'

services:
  blue.api:
    image: ${DOCKER_REGISTRY}blueapi
    build:
      context: ./BLue.Api
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  blue.identityserver:
    image: ${DOCKER_REGISTRY}blueidentityserver
    build:
      context: ./Blue.IdentityServer
      dockerfile: Dockerfile

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
